version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=test_db
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3


  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./myproject/myproject/.env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx/nginx.https.config:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app/static
    ports:
      # - "443:443"
      - "80:80"
    depends_on:
      - django
    restart:
      on-failure:5
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    #command: certonly --webroot --webroot-path /var/www/certbot/ -d example.org

volumes:
  dj_postgres_data:
  static_volume:
